version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"
  
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: postgres_service_user
      POSTGRES_PASSWORD: password
    volumes:
      - service_db_postgres-data:/var/lib/postgresql/data
    ports:
      # hostの5433とcontainerの5432をつなげる
      - "5433:5432"

  ruby_app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - kafka
      - postgres

volumes:
  service_db_postgres-data: